name: CI

on:
  pull_request:
    branches:
      - main
  release:
    types: ["published"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: cmusei/gameboard-ui

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: fetch wmks
      #   run: curl https://box.cmusei.dev/wmks-jam-v1.tar -s -o wmks.tar

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          build-args: commit=${{ github.sha }}
          labels: ${{ steps.docker_meta.outputs.labels }}
